name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: setup nodejs
      uses: actions/setup-node@v1
      with:
        node-version: 14.17.4

    - name: install deps
      run: npm install
      
    - name: build app
      run: npm run build
      
    - name: deploy app
      run: npm run deploy
